// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejxthoijjyzcwwnhpjun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqeHRob2lqanl6Y3d3bmhwanVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3ODQ5MTcsImV4cCI6MjA1NDM2MDkxN30.8FDpNuwSY8Q7SDHuzbsqJYpwI8Zr46KOLeth08YN9vE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);